/*
  SportsGuessr roster data.
  The app is intentionally split by sport so a basketball game can never
  select an NFL/MLB/soccer player. Add or replace entries in these arrays
  to expand the local roster without changing app.js.
*/
const SPORTS_PLAYERS = {
  basketball: [
    ['LeBron James','Los Angeles Lakers'],['Stephen Curry','Golden State Warriors'],['Kevin Durant','Houston Rockets'],['Jayson Tatum','Boston Celtics'],['Nikola Jokic','Denver Nuggets'],['Giannis Antetokounmpo','Milwaukee Bucks'],['Luka Doncic','Los Angeles Lakers'],['Anthony Edwards','Minnesota Timberwolves'],['Shai Gilgeous-Alexander','Oklahoma City Thunder'],['Joel Embiid','Philadelphia 76ers'],['Devin Booker','Phoenix Suns'],['Anthony Davis','Dallas Mavericks'],['Jaylen Brown','Boston Celtics'],['Damian Lillard','Portland Trail Blazers'],['Jimmy Butler','Golden State Warriors'],['Donovan Mitchell','Cleveland Cavaliers'],['Ja Morant','Memphis Grizzlies'],['Trae Young','Atlanta Hawks'],['Victor Wembanyama','San Antonio Spurs'],['Tyrese Haliburton','Indiana Pacers'],['Karl-Anthony Towns','New York Knicks'],['Jalen Brunson','New York Knicks'],['Bam Adebayo','Miami Heat'],['DeMar DeRozan','Sacramento Kings'],['Kyrie Irving','Dallas Mavericks'],['Zion Williamson','New Orleans Pelicans'],['Cade Cunningham','Detroit Pistons'],['Paolo Banchero','Orlando Magic'],['LaMelo Ball','Charlotte Hornets'],['Jaime Jaquez Jr','Miami Heat'],['Scottie Barnes','Toronto Raptors'],['Alperen Sengun','Houston Rockets'],['Domantas Sabonis','Sacramento Kings'],['DeAaron Fox','San Antonio Spurs'],['Brandon Ingram','Toronto Raptors'],['Mikal Bridges','New York Knicks'],['Jamal Murray','Denver Nuggets'],['Deandre Ayton','Portland Trail Blazers'],['Rudy Gobert','Minnesota Timberwolves'],['Draymond Green','Golden State Warriors'],['Klay Thompson','Dallas Mavericks'],['Khris Middleton','Washington Wizards'],['Jrue Holiday','Boston Celtics'],['Derrick White','Boston Celtics'],['Chet Holmgren','Oklahoma City Thunder']
  ],
  football: [
    ['Patrick Mahomes','Kansas City Chiefs'],['Josh Allen','Buffalo Bills'],['Joe Burrow','Cincinnati Bengals'],['Lamar Jackson','Baltimore Ravens'],['Jalen Hurts','Philadelphia Eagles'],['Justin Jefferson','Minnesota Vikings'],['JaMarr Chase','Cincinnati Bengals'],['CeeDee Lamb','Dallas Cowboys'],['Tyreek Hill','Miami Dolphins'],['Amon-Ra St Brown','Detroit Lions'],['Saquon Barkley','Philadelphia Eagles'],['Derrick Henry','Baltimore Ravens'],['Christian McCaffrey','San Francisco 49ers'],['Bijan Robinson','Atlanta Falcons'],['Jahmyr Gibbs','Detroit Lions'],['Travis Kelce','Kansas City Chiefs'],['George Kittle','San Francisco 49ers'],['Brock Purdy','San Francisco 49ers'],['Jayden Daniels','Washington Commanders'],['Caleb Williams','Chicago Bears'],['Joe Burrow','Cincinnati Bengals'],['Justin Herbert','Los Angeles Chargers'],['C.J. Stroud','Houston Texans'],['Jordan Love','Green Bay Packers'],['Tua Tagovailoa','Miami Dolphins'],['Micah Parsons','Dallas Cowboys'],['Myles Garrett','Cleveland Browns'],['Maxx Crosby','Las Vegas Raiders'],['Nick Bosa','San Francisco 49ers'],['Chris Jones','Kansas City Chiefs'],['Sauce Gardner','New York Jets'],['T.J. Watt','Pittsburgh Steelers'],['Aidan Hutchinson','Detroit Lions'],['Patrick Surtain II','Denver Broncos'],['D.K. Metcalf','Pittsburgh Steelers'],['DeVonta Smith','Philadelphia Eagles'],['Garrett Wilson','New York Jets'],['Drake London','Atlanta Falcons'],['Puka Nacua','Los Angeles Rams'],['Cooper Kupp','Seattle Seahawks'],['Jonathan Taylor','Indianapolis Colts'],['Josh Jacobs','Green Bay Packers'],['D.J. Moore','Chicago Bears'],['Terry McLaurin','Washington Commanders']
  ],
  soccer: [
    ['Lionel Messi','Inter Miami'],['Cristiano Ronaldo','Al Nassr'],['Kylian Mbappe','Real Madrid'],['Erling Haaland','Manchester City'],['Jude Bellingham','Real Madrid'],['Vinicius Junior','Real Madrid'],['Lamine Yamal','Barcelona'],['Harry Kane','Bayern Munich'],['Mohamed Salah','Liverpool'],['Bukayo Saka','Arsenal'],['Kevin De Bruyne','Napoli'],['Rodri','Manchester City'],['Pedri','Barcelona'],['Federico Valverde','Real Madrid'],['Florian Wirtz','Liverpool'],['Phil Foden','Manchester City'],['Cole Palmer','Chelsea'],['Martin Odegaard','Arsenal'],['Declan Rice','Arsenal'],['William Saliba','Arsenal'],['Virgil van Dijk','Liverpool'],['Alisson Becker','Liverpool'],['Thibaut Courtois','Real Madrid'],['Robert Lewandowski','Barcelona'],['Raphinha','Barcelona'],['Ousmane Dembele','Paris Saint-Germain'],['Khvicha Kvaratskhelia','Paris Saint-Germain'],['Ruben Dias','Manchester City'],['Bernardo Silva','Manchester City'],['Son Heung-min','LAFC'],['Lautaro Martinez','Inter Milan'],['Victor Osimhen','Galatasaray'],['Rodrigo','Real Madrid'],['Antoine Griezmann','Atletico Madrid'],['Rafael Leao','AC Milan'],['Achraf Hakimi','Paris Saint-Germain'],['Marquinhos','Paris Saint-Germain'],['Dani Olmo','Barcelona'],['Nico Williams','Athletic Club'],['Martin Zubimendi','Arsenal'],['Mason Mount','Manchester United'],['Bruno Fernandes','Manchester United'],['Alexander Isak','Liverpool'],['Darwin Nunez','Al Hilal'],['Joao Felix','Al Nassr']
  ],
  baseball: [
    ['Shohei Ohtani','Los Angeles Dodgers'],['Aaron Judge','New York Yankees'],['Juan Soto','New York Mets'],['Mookie Betts','Los Angeles Dodgers'],['Freddie Freeman','Los Angeles Dodgers'],['Bryce Harper','Philadelphia Phillies'],['Ronald Acuna Jr','Atlanta Braves'],['Gunnar Henderson','Baltimore Orioles'],['Bobby Witt Jr','Kansas City Royals'],['Vladimir Guerrero Jr','Toronto Blue Jays'],['Fernando Tatis Jr','San Diego Padres'],['Yordan Alvarez','Houston Astros'],['Kyle Tucker','Chicago Cubs'],['Corey Seager','Texas Rangers'],['Jose Ramirez','Cleveland Guardians'],['Elly De La Cruz','Cincinnati Reds'],['Jackson Merrill','San Diego Padres'],['Cal Raleigh','Seattle Mariners'],['Paul Skenes','Pittsburgh Pirates'],['Tarik Skubal','Detroit Tigers'],['Zack Wheeler','Philadelphia Phillies'],['Gerrit Cole','New York Yankees'],['Corbin Burnes','Arizona Diamondbacks'],['Yoshinobu Yamamoto','Los Angeles Dodgers'],['Logan Webb','San Francisco Giants'],['Chris Sale','Atlanta Braves'],['Zack Wheeler','Philadelphia Phillies'],['Adley Rutschman','Baltimore Orioles'],['Matt Olson','Atlanta Braves'],['Pete Alonso','New York Mets'],['Rafael Devers','San Francisco Giants'],['Jazz Chisholm Jr','New York Yankees'],['Corbin Carroll','Arizona Diamondbacks'],['Marcus Semien','Texas Rangers'],['Will Smith','Los Angeles Dodgers'],['Teoscar Hernandez','Los Angeles Dodgers'],['Seiya Suzuki','Chicago Cubs'],['Cody Bellinger','New York Yankees'],['Jarren Duran','Boston Red Sox'],['Riley Greene','Detroit Tigers'],['Spencer Steer','Cincinnati Reds'],['Masataka Yoshida','Boston Red Sox'],['Luis Arraez','San Diego Padres'],['Jackson Chourio','Milwaukee Brewers']
  ]
};
